trigger:
  branches:
    include:
      - main
      - AZDEVOPS-GITHUB-TEST

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Pipeline is running for GitHub → Azure DevOps"
  displayName: "Run basic test script"
